config/routes.rb
BasicStarterTemplate::Application.routes.draw do
  resources :status_updates

  resources :user_profiles

  devise_for :users
  root 'home#index'
end

app/models/status_update.rb
class StatusUpdate < ActiveRecord::Base
  belongs_to :user

  def self.reverse_chron_order
  	order(created_at: :desc)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :user_profile
	has_many :status_updates
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!
  def index
  	@status_update = StatusUpdate.new
  	@status_updates = StatusUpdate.reverse_chron_order
  end
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  before_action :set_status_update, only: [:show, :edit, :update, :destroy]

  # GET /status_updates
  # GET /status_updates.json
  def index
    @status_updates = StatusUpdate.all
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
  end

  # GET /status_updates/new
  def new
    @status_update = StatusUpdate.new
  end

  # GET /status_updates/1/edit
  def edit
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(status_update_params)
    @status_update.user = current_user

    respond_to do |format|
      if @status_update.save
        format.html { redirect_to :back, notice: 'Status update was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status_update }
      else
        format.html { render action: 'new' }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_updates/1
  # PATCH/PUT /status_updates/1.json
  def update
    respond_to do |format|
      if @status_update.update(status_update_params)
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update.destroy
    respond_to do |format|
      format.html { redirect_to status_updates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_update
      @status_update = StatusUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_update_params
      params.require(:status_update).permit(:user_id, :status_update)
    end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user_profile = UserProfile.find(params[:id])
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(current_user.user_profile)
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.user = current_user

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:starsign, :hobbies, :age, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def find_user_name(status_update)
		@status_update = status_update
		@user = User.find(status_update.User_id)
		@user.user_profile.name
	end
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/home/index.html.erb
<div class="row">
	<div class="col-md-4 menu">

	</div>
	<div class="col-md-8">
		<%= render 'status_updates/form' %>
		<hr>
		<% @status_updates.each do |status_update| %>
			<div class="panel">
				<p><%= status_update.user.user_profile.name %></p>
				<p><%= status_update.status_update %></p>
				<p>Posted on: <%= status_update.created_at.strftime("%d %b %y") %></p>
			</div>
		<% end %>

	</div>
</div>
<div class="jumbotron">
<h1><i class="fa fa-group"></i> The Startup Community</h1>


<p class="lead">Join now to connect with like-minded tech entrepreneurs and grow your startup's brand.</p>

<h2>Why should you join?</h2>
<ol>
<li>Create a profile for yourself - have it viewed by journalists, potential co-founders or investors.</li>
<li>Let people know your startup exists</li>
<li>Connect and network with other entrepreneurs who share your interests</li>
<li>Share the latest news for your startup</li>
<li>Tell people about your upcoming events</li>
<li>Ask and answer startup questions</li>
<li>Join groups of local entrepreneurs</li>
</ol>
<%= link_to "JOIN NOW", new_user_registration_path, class: 'btn btn-lg btn-success' %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Menu</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://thestartupcommunity.com">The Startup Community</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#"><i class="fa fa-link"></i> Link</a></li>
        
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Edit my profile', edit_user_profile_path(current_user.user_profile) %></li>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "The Coder Factory" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "The Coder Factory" %>">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>
<body>
	<%= render 'layouts/navigation' %>
	<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/status_updates/_form.html.erb
<%= simple_form_for(@status_update) do |f| %>
  <%= f.error_notification %>

  
  <div class="form-group">
    <%= f.input :status_update, input_html: { class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing status_update</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html.erb
<h1>Listing status_updates</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status update</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_updates.each do |status_update| %>
      <tr>
        <td><%= status_update.user.user_profile.name %></td>
        <td><%= status_update.status_update %></td>
        <td><%= link_to 'Show', status_update %></td>
        <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
        <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status update', new_status_update_path %>

app/views/status_updates/new.html.erb
<h1>New status_update</h1>

<%= render 'form' %>

<%= link_to 'Back', status_updates_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @status_update.user %>
</p>

<p>
  <strong>Status update:</strong>
  <%= @status_update.status_update %>
</p>

<%= link_to 'Edit', edit_status_update_path(@status_update) %> |
<%= link_to 'Back', status_updates_path %>

app/views/user_profiles/_form.html.erb
<%= simple_form_for(@user_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :starsign, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :hobbies, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :age, input_html: { class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <thead>
    <tr>
      <th>Starsign</th>
      <th>Hobbies</th>
      <th>Age</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.starsign %></td>
        <td><%= user_profile.hobbies %></td>
        <td><%= user_profile.age %></td>
        <td><%= user_profile.name %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-info">
	<div class="panel-heading">
		<p class="panel-title all-caps">
		  
		  <%= @user_profile.name %>
		</p>
	</div>
	<div class="panel-body">
		<p>
		  <strong>Starsign:</strong>
		  <%= @user_profile.starsign %>
		</p>
		<p>
		  <strong>Hobbies:</strong>
		  <%= @user_profile.hobbies %>
		</p>
		<p>
		  <strong>Age:</strong>
		  <%= @user_profile.age %>
		</p>
		<% if user_signed_in? %>
			<% if @user_profile == current_user.user_profile %>
				<%= link_to 'Edit', edit_user_profile_path(@user_profile), class: 'btn btn-info' %>
			<% end %>
		<% end %>
	</div>
</div>